# <div style="text-align: center"> Corso di Python: Collegio Mazza  A.A. 2023-2024 </div>

## <div style="text-align: center"> Commissione Informatica: 19/03/2024 </div>

# <div style="text-align: center"> Python Liste & `Numpy` array </div>

### Cos'è una lista e cos'è un `Numpy array`? 

In [1]:
import numpy as np

Qual è il vantaggio di usare un Numpy array rispetto ad una tradizionale lista in python? L'ottimizzazione

Ripassiamo cos'è un `for loop`

1. Esercizio: Scrivere una funzione/codice che prenda il quadrato di tutti gli elementi di un array in python. Utilizza come array:
    * Una lista python;
    * Un Numpy array.
2. Esercizio: Continuando l'esercizio sopra, somma tutti i numeri dell'array.

In [12]:
lista = [1, 2, 3, 4, 5, 6]
lista_res = []
for el in lista:
    lista_res.append(el**2)
lista_res

[1, 4, 9, 16, 25, 36]

In [20]:
array = np.array(lista)
array_res = array ** 2
array_res

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [14]:
somma = 0
for el in lista_res:
    somma += el
somma

91

In [27]:
np.sum(lista_res)

91

In [21]:
array_res.sum()

91

In [29]:
array_res = array_res.reshape((2, 3))
array_res, array_res.sum(axis=0)

(array([[ 1,  4,  9],
        [16, 25, 36]], dtype=int32),
 array([17, 29, 45], dtype=int32))

In [31]:
dati = np.random.normal(size=(100, 10))
np.savetxt('dati.txt', dati)

In [33]:
import_dati = np.loadtxt('dati.txt')
import_dati.shape

(100, 10)

3. Esercizio: Trovare: 
    * Numero di righe;
    * Numero di colonne;
    * Media totale e per riga/colonna
    del seguente array

    ```python
    m = np.arange(12).reshape((3, 4))
    ```

In [40]:
m = np.arange(12).reshape((3, 4))
print("Il numero di righe della matrice m è", m.shape[0])
print("Il numero delle colonne della matrice m è", m.shape[1])

Il numero di righe della matrice m è 3
Il numero delle colonne della matrice m è 4


In [43]:
m.mean(), m.mean(axis=0), m.mean(axis=1)

(5.5, array([4., 5., 6., 7.]), array([1.5, 5.5, 9.5]))

### Da un array posso creare una matrice e/o un tensore? 

### Traces and determinants

### Autovalori e autovettori

### Abbiamo così risolto il problema $$\mathbb{A}\cdot \vec{v}_i = \lambda_i \cdot \vec{v}_i,$$ trovando la matrice $\mathbb{V}$ che ha per colonne gli autovettori di A: 

\begin{equation*}
    \mathbb{V} = 
    \begin{bmatrix}
        v_1^{(1)} & v_2^{(1)} & v_3^{(1)} \\ 
        v_1^{(2)} & v_2^{(2)} & v_3^{(2)} \\ 
        v_1^{(3)} & v_2^{(3)} & v_3^{(3)}  
    \end{bmatrix}
\end{equation*}

### pertanto abbiamo risolto il problema $$ \mathbb{A}\cdot \mathbb{V} = \mathbb{V} \cdot \Lambda,$$ dove $\Lambda$ è la matrice diagonale di autovalori. Si può riottenere la matrice $ \mathbb{A}$ di partenza invertendo questa relazione: $$\boxed{\mathbb{A} = \mathbb{V} \cdot \Lambda \cdot \mathbb{V}^{-1}} $$ 

4. Esercizio: Usando `np.linspace`, crea un array di 100 numeri tra nell'intervallo $[0, 2\pi]$ (estremi inclusi).
    * Estrai i valori ogni **10** elementi;
    * Inverti l'array;
    * Estrai gli elementi la cui differenza in valore assoluto tra le funzioni `sin()` e `cos()` (valutate nello stesso elemento) è più piccola di 0.1: 
    $$\vert\sin(\theta)-\cos(\theta)\vert < 0.1, \quad \forall \theta \in \text{array}$$

5. Esercizio: Crea una matrice contenente le prime 10 tabelline. 
    * Calcolane la traccia;
    * Estraine la diagonale maggiore e l'anti-diagonale maggiore 

6. Esercizio: Crea **3** matrici $\mathcal{M}_{3\times 3}$ random (usa il modulo `np.random`):
    * Trova la matrice data dal prodotto delle 3 matrici;
    * Prova che la traccia della matrice così ottenuta è uguale alla somma dei suoi autovalori;
    * Prova che il determinante della matrice così ottenuta è pari al prodotto dei suoi autovalori.  