# <div style="text-align: center"> Corso di Python: Collegio Mazza  A.A. 2023-2024 </div>

## <div style="text-align: center"> Commissione Informatica: 19/03/2024 </div>

# <div style="text-align: center"> Python Liste & `Numpy` array </div>

### Cos'è una lista e cos'è un `Numpy array`? 

In [1]:
lista = [0, 1, 3, 'a', 'ciao']  # contenitore di elementi di diverso tipo
lista

[0, 1, 3, 'a', 'ciao']

In [2]:
import numpy as np

In [3]:
array = np.array(lista)
array   # converte tutto in elementi di un unico tipo: perché?

array(['0', '1', '3', 'a', 'ciao'], dtype='<U11')

In [4]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

Qual è il vantaggio di usare un Numpy array rispetto ad una tradizionale lista in python? L'ottimizzazione

In [5]:
array = np.zeros(shape=6, dtype=int)
array[2] = 5
array
array.shape
array = array.reshape(2, 3)
array

array([[0, 0, 5],
       [0, 0, 0]])

Ripassiamo cos'è un `for loop`

In [6]:
for el in lista:
    print(el)

for i, el in enumerate(array):
    print(i, el)

0
1
3
a
ciao
0 [0 0 5]
1 [0 0 0]


1. Esercizio: Scrivere una funzione/codice che prenda il quadrato di tutti gli elementi di un array in python. Utilizza come array:
    * Una lista python;
    * Un Numpy array.
2. Esercizio: Continuando l'esercizio sopra, somma tutti i numeri dell'array.

3. Trovare: 
    * Numero di righe;
    * Numero di colonne;
    * Media totale e per riga/colonna
    del seguente array

    ```python
    m = np.arange(12).reshape((3, 4))
    ```

### Da un array posso creare una matrice e/o un tensore? 

In [7]:
# generate 4 sequences of 10 random numbers (flat between 0 and 1)
n, p = 10, 4
v = np.random.random((p, n))
v

array([[0.98473755, 0.02411954, 0.59030794, 0.21345877, 0.2670087 ,
        0.97885427, 0.38591143, 0.08315964, 0.12061367, 0.37870526],
       [0.67085896, 0.59024632, 0.01657667, 0.68444312, 0.55679744,
        0.6537002 , 0.60327153, 0.88699786, 0.92651813, 0.94189362],
       [0.53769739, 0.74188835, 0.20231346, 0.44420625, 0.5452683 ,
        0.63775342, 0.82747138, 0.87134906, 0.16488366, 0.25884835],
       [0.23350462, 0.51858126, 0.73062534, 0.21371953, 0.36635623,
        0.38820946, 0.07839505, 0.24908151, 0.38031449, 0.96076526]])

In [8]:
np.cov(v)

array([[ 1.20666896e-01, -2.61959731e-02, -7.28176745e-03,
        -1.13813410e-04],
       [-2.61959731e-02,  7.05594614e-02,  8.68757389e-03,
        -9.57572362e-03],
       [-7.28176745e-03,  8.68757389e-03,  6.47681858e-02,
        -4.01702003e-02],
       [-1.13813410e-04, -9.57572362e-03, -4.01702003e-02,
         6.96320803e-02]])

### Traces and determinants

In [9]:
A = np.ones(shape=(3, 3))
A.trace(), np.trace(A), np.linalg.det(A), np.diag(A)

(3.0, 3.0, 0.0, array([1., 1., 1.]))

In [10]:
n = 6
M = np.random.randint(100, size=(n,n))
print(M, '\n')
print('determinant:', np.linalg.det(M), '\n')
print('trace:', M.trace(), '\n')

[[18 95 81  7 39 10]
 [55 83 64 68 57 79]
 [33 35 39 98 34 97]
 [16 46 35 88 89 67]
 [56 28 91 56  8  9]
 [38 26 14 95 64 60]] 

determinant: 27458485612.99993 

trace: 296 



### Autovalori e autovettori

In [11]:
A = np.array([[0, 1, 1], [2, 1, 0], [3, 4, 5]])
print(f'A matrix: \n{A}')
print(f'det(A) = {np.linalg.det(A)}\n')


l, V = np.linalg.eig(A)
print(f'A eigenvectors:\n{V}')
print(f'A eigenvalues:\n{l}')

A matrix: 
[[0 1 1]
 [2 1 0]
 [3 4 5]]
det(A) = -5.000000000000002

A eigenvectors:
[[ 1.80228488e-01  6.72063326e-01 -2.06609884e-16]
 [ 7.42582208e-02 -7.24947536e-01 -7.07106781e-01]
 [ 9.80817725e-01  1.50936928e-01  7.07106781e-01]]
A eigenvalues:
[ 5.85410197 -0.85410197  1.        ]


### Abbiamo così risolto il problema $$\mathbb{A}\cdot \vec{v}_i = \lambda_i \cdot \vec{v}_i,$$ trovando la matrice $\mathbb{V}$ che ha per colonne gli autovettori di A: 

\begin{equation*}
    \mathbb{V} = 
    \begin{bmatrix}
        v_1^{(1)} & v_2^{(1)} & v_3^{(1)} \\ 
        v_1^{(2)} & v_2^{(2)} & v_3^{(2)} \\ 
        v_1^{(3)} & v_2^{(3)} & v_3^{(3)}  
    \end{bmatrix}
\end{equation*}

### pertanto abbiamo risolto il problema $$ \mathbb{A}\cdot \mathbb{V} = \mathbb{V} \cdot \Lambda,$$ dove $\Lambda$ è la matrice diagonale di autovalori. Si può riottenere la matrice $ \mathbb{A}$ di partenza invertendo questa relazione: $$\boxed{\mathbb{A} = \mathbb{V} \cdot \Lambda \cdot \mathbb{V}^{-1}} $$ 

In [12]:
Lambda = np.zeros_like(V)
np.fill_diagonal(Lambda, l)
V @ Lambda @ np.linalg.inv(V)

array([[ 5.92791796e-16,  1.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00, -4.69761657e-16],
       [ 3.00000000e+00,  4.00000000e+00,  5.00000000e+00]])

In [13]:
np.dot(V, np.dot(np.diag(np.real_if_close(l)), np.linalg.inv(V)))

array([[ 7.03814098e-16,  1.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00, -4.93155865e-16],
       [ 3.00000000e+00,  4.00000000e+00,  5.00000000e+00]])

4. Esercizio: Usando `np.linspace`, crea un array di 100 numeri tra nell'intervallo $[0, 2\pi]$ (estremi inclusi).
    * Estrai i valori ogni **10** elementi;
    * Inverti l'array;
    * Estrai gli elementi la cui differenza in valore assoluto tra le funzioni `sin()` e `cos()` (valutate nello stesso elemento) è più piccola di 0.1: 
    $$\vert\sin(\theta)-\cos(\theta)\vert < 0.1, \quad \forall \theta \in \text{array}$$

In [14]:
array = np.linspace(0, 2.*np.pi+1/1000, 100)
array[::10]
array[::-1]
mask = [index for index, theta in enumerate(array) if np.abs(np.sin(theta)-np.cos(theta)) < 0.1]
array[mask]

array([0.76171943, 0.82519605, 3.87207378, 3.93555039])

5. Esercizio: Crea una matrice contenente le prime 10 tabelline. 
    * Calcolane la traccia;
    * Estraine la diagonale maggiore e l'anti-diagonale maggiore 

In [15]:
tabelline_in = np.array(range(1, 11))
tabelline = np.outer(tabelline_in, tabelline_in)
# in alternativa:
tabelline = [[t*val for t in tabelline_in] for val in tabelline_in]
tabelline = np.array(tabelline)
tabelline

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [16]:
np.diag(tabelline), np.diag(tabelline[::-1])

(array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]),
 array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10]))

6. Esercizio: Crea **3** matrici $\mathcal{M}_{3\times 3}$ random (usa il modulo `np.random`):
    * Trova la matrice data dal prodotto delle 3 matrici;
    * Prova che la traccia della matrice così ottenuta è uguale alla somma dei suoi autovalori;
    * Prova che il determinante della matrice così ottenuta è pari al prodotto dei suoi autovalori.  

In [17]:
a = np.random.normal(size=(3, 3))
b = np.random.normal(size=(3, 3))
c = np.random.normal(size=(3, 3))
matrix = a @ b @ c

eig, _ = np.linalg.eig(matrix)
print(f'Matrix trace = {np.trace(matrix)}\nSum of eigenvalues = {np.sum(eig)}')
print(f'Matrix determinat = {np.linalg.det(matrix)}\nProduct of eigenvalues = {np.prod(eig)}')

Matrix trace = 4.255714850459592
Sum of eigenvalues = 4.255714850459595
Matrix determinat = -0.21928283741760474
Product of eigenvalues = -0.2192828374176049
